src/apps/backend/models/User.php
<?php
namespace code2magic\baseApp\backend\models;

/**
 * Class User
 *
 * @property string $backendName
 *
 * @package code2magic\baseApp\backend\models
 */
class User extends \common\models\User
{
    /**
     * @return string
     */
    public function getBackendName(): string
    {
        /** @var User $item */
        return "{$this->fullName} ({$this->username})";
    }
}

src/apps/backend/models/UserForm.php
<?php

namespace code2magic\baseApp\backend\models;

use borales\extensions\phoneInput\PhoneInputValidator;
use code2magic\catalog\backend\models\UserCustomerGroup;
use code2magic\geo\backend\models\City;
use code2magic\baseApp\models\User;
use Yii;
use yii\base\Exception;
use yii\base\Model;
use yii\base\UnknownMethodException;
use yii\base\UnknownPropertyException;
use yii\helpers\ArrayHelper;

/**
 * Create user form
 */
class UserForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $password_confirm;
    public $status;
    public $roles;

    public $firstname;
    public $middlename;
    public $lastname;
    public $address_region;
    public $address_city;
    public $geo_city_id;
    public $address_street;
    public $address_building;
    public $address_apt;
    public $phone;
    public $catalog_user_customer_group_id;
    public $is_subscribed;
    public $comment;
    public $birthday;

    private $model;

    /**
     * @param string $name
     *
     * @return mixed
     */
    public function __get($name)
    {
        try {
            return parent::__get($name);
        } catch (UnknownPropertyException $e) {
            return $this->model->$name;
        }
    }

    public function __set($name, $value)
    {
        try {
            return parent::__set($name, $value);
        } catch (UnknownPropertyException $e) {
            $this->model->$name = $value;
        }
    }

    public function __call($name, $params)
    {
        try {
            return parent::__call($name, $params);
        } catch (UnknownMethodException $e) {
            return \call_user_func([$this->model, $name], $params);
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['catalog_user_customer_group_id'], 'integer'],
            [['catalog_user_customer_group_id'], 'default', 'value' => function ($model) {
                return ArrayHelper::getValue(UserCustomerGroup::getDefault(), 'id');
            }],
            [['username',], 'filter', 'filter' => 'trim'],
            [['username',], 'required'],
            [['username',], 'unique', 'targetClass' => User::class, 'filter' => function ($query) {
                if (!$this->getModel()->isNewRecord) {
                    $query->andWhere(['not', ['id' => $this->getModel()->id]]);
                }
            }],
            [['username',], 'string', 'min' => 2, 'max' => 255],
            [
                [
                    'firstname',
                    'lastname',
                    'middlename',
                    'address_region',
                    'address_city',
                    'address_apt',
                    'address_street',
                    'address_building',
                ],
                'string',
                'max' => 255,
            ],
            [
                [
                    'firstname',
                    'lastname',
                    'middlename',
                    'address_region',
                    'address_city',
                    'address_apt',
                    'address_street',
                    'address_building',
                    'phone',
                    'comment',
                ],
                'default',
                'value' => '',
            ],
            [['comment',], 'string',],
            [['birthday',], 'date',],
            [['geo_city_id',], 'exist', 'targetClass' => City::class, 'targetAttribute' => ['geo_city_id' => 'id']],
            [['is_subscribed',], 'boolean'],
            [['is_subscribed',], 'default', 'value' => 1],
            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'unique', 'targetClass' => User::class, 'filter' => function ($query) {
                if (!$this->getModel()->isNewRecord) {
                    $query->andWhere(['not', ['id' => $this->getModel()->id]]);
                }
            }],

            ['password', 'required', 'on' => 'create'],
            ['password', 'string', 'min' => 6],
            [['password_confirm'], 'compare', 'compareAttribute' => 'password'],
            ['password_confirm', 'required', 'when' => function ($model) {
                return ($model->password) ? 1 : 0;
            }, 'whenClient' => "function(attribute, value){return $('#accountform-password').val()?1:0;}"],
            [['status'], 'integer'],
            [['phone'], 'string'],
            [['phone'], PhoneInputValidator::class],
            [['roles'], 'each', 'rule' => ['in', 'range' => function ($model, $attribute) {
                return ArrayHelper::getColumn(
                    Yii::$app->authManager->getRoles(),
                    'name'
                );
            }],
            ],
        ];
    }

    /**
     * @return User
     */
    public function getModel()
    {
        if (!$this->model) {
            $this->model = new User();
        }
        return $this->model;
    }

    /**
     * @param User $model
     *
     * @return mixed
     */
    public function setModel($model)
    {
        $this->load($model->attributes, '');
        $this->load($model->userProfile->attributes, '');
        $this->model = $model;
        $this->roles = ArrayHelper::getColumn(
            Yii::$app->authManager->getRolesByUser($model->getId()),
            'name'
        );
        return $this->model;
    }

    /**
     * @return City
     */
    public function getCity()
    {
        return ArrayHelper::getValue($this->getModel(), ['userProfile', 'city']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'username' => Yii::t('common', 'Username'),
            'email' => Yii::t('common', 'E-mail'),
            'status' => Yii::t('common', 'Status'),
            'password' => Yii::t('common', 'Password'),
            'roles' => Yii::t('common', 'Roles'),
            'birthday' => Yii::t('model_labels', 'Birthday'),
            'address_region' => Yii::t('model_labels', 'Address Region'),
            'address_building' => Yii::t('model_labels', 'Address Building'),
            'address_city' => Yii::t('model_labels', 'Address City'),
            'geo_city_id' => Yii::t('model_labels', 'City'),
            'address_street' => Yii::t('model_labels', 'Address Street'),
            'address_apt' => Yii::t('model_labels', 'Address Apt'),
            'firstname' => Yii::t('model_labels', 'Firstname'),
            'lastname' => Yii::t('model_labels', 'Lastname'),
            'middlename' => Yii::t('model_labels', 'Middlename'),
            'phone' => Yii::t('model_labels', 'Phone'),
            'comment' => Yii::t('model_labels', 'Comment'),
            'password_confirm' => Yii::t('backend', 'Password Confirm'),
            'catalog_user_customer_group_id' => Yii::t('model_labels', 'User customer group'),
            'is_subscribed' => Yii::t('frontend/user/model_labels', 'Is Subscribed'),

        ];
    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     * @throws Exception
     */
    public function save()
    {
        if ($this->validate()) {
            $model = $this->getModel();
            $isNewRecord = $model->getIsNewRecord();
            $model->username = $this->username;
            $model->email = $this->email;
            $model->status = $this->status;
            if ($this->password) {
                $model->setPassword($this->password);
            }
            $transaction = Yii::$app->db->beginTransaction();
            try {
                if (!$model->save()) {
                    throw new Exception('Model not saved');
                }
                if ($isNewRecord) {
                    $model->afterSignup($this->attributes);
                } else {
                    $model->userProfile->load($this->attributes, '');
                    if(!array_key_exists($model->userProfile->locale, \code2magic\i18n\helpers\Locale::getLanguages())){
                        $model->userProfile->locale = null;
                    }
                    if (!$model->userProfile->save()) {
                        throw new Exception('Model not saved');
                    }
                }
                $auth = Yii::$app->authManager;
                $auth->revokeAll($model->getId());

                if ($this->roles && \is_array($this->roles)) {
                    foreach ($this->roles as $role) {
                        $auth->assign($auth->getRole($role), $model->getId());
                    }
                }
            } catch (\Exception $e) {
                $this->addErrors(['Exception' => $e->getMessage()]);
                $transaction->rollBack();
                return false;
            }
            $transaction->commit();
            return !$model->hasErrors();
        }
        return null;
    }
}

src/apps/backend/controllers/UserController.php
<?php

namespace code2magic\baseApp\backend\controllers;

use code2magic\baseApp\backend\models\search\UserSearch;
use code2magic\baseApp\backend\models\User;
use code2magic\baseApp\backend\models\UserForm;
use code2magic\catalog\backend\models\Product;
use code2magic\catalog\models\PromotionCart;
use code2magic\checkout\backend\models\Order;
use code2magic\checkout\frontend\components\cart\ShoppingCartWithDb;
use code2magic\baseApp\models\UserWishlist;
use werewolf8904\cmscore\controllers\BackendController;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BackendController
{
    public $layout = 'common';

    /** @inheritDoc */
    public function actions()
    {
        $actions = parent::actions();
        $actions['list'] = [
            'class' => \code2magic\core\web\actions\Select2Action::class,
            'getQuery' => function ($words) {
                return User::find()
                    ->joinWith(['userProfile p'])
                    ->andFilterWhere(['or',
                        ['like', 'username', $words],
                        ['like', 'email', $words],
                        ['or like', 'p.firstname', $words],
                        ['or like', 'p.middlename', $words],
                        ['or like', 'p.lastname', $words],
                    ]);
            },
            'prepareText' => 'backendName',
        ];
        return $actions;
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post',],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     * @throws \yii\base\InvalidArgumentException
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', compact('searchModel', 'dataProvider'));
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws \yii\base\InvalidArgumentException
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $this->view->params['returnUrl'] = $this->getReturn();
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::find()->andWhere(['id' => $id])->one()) !== null) {
            if (Yii::$app->user->can('administrator')) {
                return $model;
            }
            if (\count(array_intersect_key(Yii::$app->authManager->getRolesByUser($model->id), ['administrator' => 'administrator', 'manager' => 'manager'])) < 1) {
                return $model;
            }
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $this->view->params['returnUrl'] = $this->getReturn();
        $model = new UserForm();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->keyStorage->get('backend.stay_after_save', true) || array_key_exists('stay', Yii::$app->request->post())) {
                Yii::$app->session->setFlash('alert', [
                    'body' => Yii::t('backend', 'Successfully saved'),
                    'options' => ['class' => 'alert alert-success']
                ]);

            } else {
                return $this->goReturn();
            }
        }
        return $this->render('create', [
            'model' => $model,
            'orders' => [],
            'wishlists' => [],
            'cart_positions' => [],
            'availablePromotionCart' => [],
            'usedPromotionCart' => [],
            'roles' => $this->getRoles(),
        ]);
    }

    /**
     * @return array
     */
    protected function getRoles()
    {
        if (Yii::$app->user->can('administrator')) {
            $roles = Yii::$app->authManager->getRoles();
        } else {
            $roles = [];
        }
        return ArrayHelper::map($roles, 'name', function ($array) {
            return $array->name . ' ' . $array->description;
        });
    }

    /**
     * Updates an existing User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $this->view->params['returnUrl'] = $this->getReturn();
        $model = new UserForm();
        $model->setModel($this->findModel($id));
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (
                Yii::$app->keyStorage->get('backend.stay_after_save', true)
                || array_key_exists('stay', Yii::$app->request->post())
            ) {
                Yii::$app->session->setFlash('alert', [
                    'body' => Yii::t('backend', 'Successfully saved'),
                    'options' => ['class' => 'alert alert-success']
                ]);
                return $this->refresh('#' . Yii::$app->request->post($this->stay_post_parameter));
            }
            return $this->goReturn();
        }
        $orders = Order::find()->andWhere(['user_id' => $model->id,])->all();
        $cart = new ShoppingCartWithDb(['user' => $model->getModel()->userProfile,]);
        $cart_positions = $cart->positions;
        $wishlists = UserWishlist::find()->andWhere(['user_id' => $model->id])->with(['product' => function ($query) {
            $query->modelClass = Product::class;
            return $query;
        },])->all();
        $availablePromotionCart = PromotionCart::find()
            ->available(false, false)
            ->used(false)->all();
        $usedPromotionCart = PromotionCart::find()
            ->available(false, false)
            ->used(true)->all();
        return $this->render('update', ArrayHelper::merge(
            compact('model', 'orders', 'wishlists', 'cart_positions', 'availablePromotionCart', 'usedPromotionCart'),
            [
                'roles' => $this->getRoles(),
            ]
        ));
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        Yii::$app->authManager->revokeAll($id);
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }
}

src/apps/backend/views/user/_form.php
<?php
/**
 * @var $this yii\web\View
 * @var $model code2magic\baseApp\backend\models\UserForm
 * @var $form yii\bootstrap\ActiveForm
 * @var $roles yii\rbac\Role[]
 * @var $permissions yii\rbac\Permission[]
 */

use kartik\tabs\TabsX;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>
<div class="user-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model); ?>
    <?php
    $tabs = [
        [
            'label' => Yii::t('backend', 'Main'),
            'content' => $this->render('_main_tab', compact('form', 'model')),
        ],
        [
            'label' => Yii::t('backend', 'User Profile'),
            'content' => $this->render('_profile_tab', compact('form', 'model')),
        ],
        [
            'label' => Yii::t('backend', 'Prices'),
            'content' => $this->render('_price_tab', compact('form', 'model')),
        ],
    ];
    if (!$model->getModel()->getIsNewRecord()) {
        $tabs[] = [
            'label' => Yii::t('backend', 'Orders and wishlists'),
            'content' => $this->render(
                '_order_tab',
                compact(
                    'form',
                    'model',
                    'orders',
                    'wishlists',
                    'cart_positions'
                )
            ),
            'visible' => !$model->getModel()->getIsNewRecord(),
        ];
    }
    if (Yii::$app->user->can('administrator')) {
        $tabs[] = [
            'label' => Yii::t('backend', 'Roles'),
            'content' => $this->render('_roles_tab', compact('form', 'model', 'roles')),
        ];
    }
    if (!$model->getModel()->getIsNewRecord()) {
        $tabs[] = [
            'label' => Yii::t('backend', 'Promotion Cart'),
            'content' => $this->render('_promotion_cart_tab', compact('form', 'model', 'availablePromotionCart', 'usedPromotionCart')),
            'visible' => Yii::$app->user->can('administrator'),
        ];
    }
    echo TabsX::widget([
        'items' => $tabs,
        'enableStickyTabs' => true,
        'stickyTabsOptions' => [
            'selectorAttribute' => 'data-target',
            'backToTop' => false,
        ],
        'position' => TabsX::POS_ABOVE,
        'id' => 'main_tabs',
        'encodeLabels' => false,
    ]);
    ?>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-primary', 'name' => 'signup-button',]) ?>
        <?= Html::submitButton(Yii::t('backend', 'Save and stay'), ['class' => 'btn btn-success', 'name' => 'stay',]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

src/apps/backend/views/user/_main_tab.php
<?php
/**
 * @var \yii\web\View $this
 * @var yii\bootstrap\ActiveForm $form
 * @var \backend\models\UserForm $model
 */
?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Yii::t('backend', 'Main data') ?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body" style="">
        <?= $form->field($model, 'username', ['options' => ['autocomplete' => 'false',],]) ?>
        <?= $form->field($model, 'email', ['options' => ['autocomplete' => 'false',],]) ?>
        <?= $form->field($model, 'password', ['options' => ['autocomplete' => 'false',],])
            ->passwordInput() ?>
        <?= $form->field($model, 'password_confirm', ['options' => ['autocomplete' => 'false',],])
            ->passwordInput() ?>
        <?= $form->field($model, 'status')
            ->dropDownList(\common\models\User::statuses()) ?>
    </div>
</div>

src/apps/backend/views/user/_order_tab.php
<?php
/**
 * @var \yii\web\View $this
 * @var \backend\models\UserForm $model
 * @var \code2magic\checkout\backend\models\Order[] $orders
 * @var \common\models\UserWishlist[] $wishlists
 * @var \code2magic\checkout\frontend\models\CartPosition[] $cart_positions
 */

use yii\helpers\Url;

?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Yii::t('backend', 'User Orders') ?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
        <div class="table-responsive">
            <table class="table table-striped no-margin">
                <thead>
                <tr>
                    <th><?= Yii::t('backend', 'Order Id') ?></th>
                    <th><?= Yii::t('backend', 'Status') ?></th>
                    <th><?= Yii::t('backend', 'Total') ?></th>
                    <th><?= Yii::t('backend', 'Craeted at') ?></th>
                    <th><?= Yii::t('backend', 'Finished at') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($orders as $order): ?>
                    <tr>
                        <td>
                            <a href="<?= Url::toRoute(['/checkout/order/update', 'id' => $order->id]) ?>">
                                <?= $order->id ?>
                            </a>
                        </td>
                        <td><span class="label label-info"><?= $order->orderStatus->name ?></span></td>
                        <td><?= $order->getTotal_cost() ?></td>
                        <td><?= $order->created_at ?></td>
                        <td><?= $order->updated_at ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.box-body -->
    <!-- /.box-footer -->
</div>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Yii::t('backend', 'User Shopping cart') ?></h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>

        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
        <div class="table-responsive">
            <table class="table table-striped no-margin">
                <thead>
                <tr>
                    <th><?= Yii::t('backend', 'Product') ?></th>
                    <th><?= Yii::t('backend', 'Quantity') ?></th>
                    <th><?= Yii::t('backend', 'Base price') ?></th>
                    <th><?= Yii::t('backend', 'Price') ?></th>
                    <th><?= Yii::t('backend', 'Total cost') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($cart_positions as $position): ?>
                    <tr>
                        <td>
                            <a href="<?= Url::toRoute(['/catalog/product/update', 'id' => $position->getProductId()]) ?>">
                                <?= $position->getName() ?>
                            </a>
                        </td>

                        <td><?= $position->quantity ?></td>
                        <td><?= $position->getPrice(false) ?></td>
                        <td><?= $position->getPrice() ?></td>
                        <td><?= $position->getCost() ?></td>

                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.box-body -->
    <!-- /.box-footer -->
</div>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Yii::t('backend', 'User Wishlist') ?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
        <div class="table-responsive">
            <table class="table table-striped no-margin">
                <thead>
                <tr>
                    <th><?= Yii::t('backend', 'Product') ?></th>
                    <th><?= Yii::t('backend', 'Created at') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($wishlists as $wishlist): ?>
                    <tr>
                        <td>
                            <a href="<?= Url::toRoute([
                                '/catalog/product/update', 'id' => $wishlist->catalog_product_id
                            ]) ?>">
                                <?= \yii\helpers\ArrayHelper::getValue($wishlist, ['product', 'name',], '-') ?>
                            </a>
                        </td>
                        <td><?= Yii::$app->formatter->asDatetime($wishlist->created_at) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.box-body -->
    <!-- /.box-footer -->
</div>

src/apps/backend/views/user/_roles_tab.php
<?php
/**
 * @var yii\web\View $this
 * @var yii\bootstrap\ActiveForm $form
 * @var code2magic\baseApp\backend\models\UserForm $model
 * @var array $roles
 */
?>
<?= $form->field($model, 'roles')->checkboxList($roles) ?>

src/apps/backend/views/user/index.php
<?php
/**
 * @var yii\web\View $this
 * @var code2magic\baseApp\backend\models\search\UserSearch $searchModel
 * @var yii\data\ActiveDataProvider $dataProvider
 */

use code2magic\core\grid\column\Enum;
use code2magic\baseApp\models\User;
use trntv\yii\datetime\DateTimeWidget;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\web\JsExpression;

$this->title = Yii::t('backend', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginContent('@backend/views/_common/box-wrap.php'); ?>
<div class="user-index">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <p>
        <?= Html::a(Yii::t('backend', 'Create {modelClass}', [
            'modelClass' => Yii::t('backend', 'User'),
        ]), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => [
            'class' => 'grid-view table-responsive'
        ],
        'columns' => [
            //[
            //    'format' => 'raw',
            //    'label' => Yii::t('backend', 'Avatar'),
            //    'value' => function ($model, $key, $index, $column) {
            //        return Html::img($model->userProfile->getAvatar('/img/anonymous.jpg'), ['style' => 'max-width: 100px;max-height: 100px;']);
            //    },
            //],
            //'id',
            [
                'format' => 'raw',
                'attribute' => 'fullname',
                'label' => $searchModel->getAttributeLabel('fullname'),
                'value' => function ($model, $key, $index, $column) {
                    /** @var User $model */
                    return Html::a($model->publicIdentity, ['user/update', 'id' => $model->id,]);
                },
            ],
            'email:email',
            [
                'attribute' => 'phone',
                'value' => 'userProfile.phone',
                'label' => $searchModel->getAttributeLabel('phone'),
            ],
            [
                'attribute' => 'user_customer_group',
                'value' => 'userProfile.userCustomerGroupI18n.name',
                'filter' => \yii\helpers\ArrayHelper::map(
                    \code2magic\catalog\backend\models\UserCustomerGroup::find()->localized()->all(),
                    'id',
                    'name'
                ),
                'label' => $searchModel->getAttributeLabel('user_customer_group'),
            ],
            [
                'attribute' => 'region',
                'value' => 'userProfile.city.region.name',
                'label' => $searchModel->getAttributeLabel('region'),
            ],
            [
                'attribute' => 'city',
                'value' => 'userProfile.city.name',
                'label' => $searchModel->getAttributeLabel('city'),
            ],
            [
                'class' => Enum::class,
                'attribute' => 'status',
                'enum' => User::statuses(),
                'filter' => User::statuses(),
            ],
            [
                'attribute' => 'created_at',
                'format' => 'datetime',
                'filter' => DateTimeWidget::widget([
                    'model' => $searchModel,
                    'attribute' => 'created_at',
                    'phpDatetimeFormat' => 'dd.MM.yyyy',
                    'momentDatetimeFormat' => 'DD.MM.YYYY',
                    'clientEvents' => [
                        'dp.change' => new JsExpression('(e) => $(e.target).find("input").trigger("change.yiiGridView")'),
                    ],
                ])
            ],
            [
                'attribute' => 'logged_at',
                'format' => 'datetime',
                'filter' => DateTimeWidget::widget([
                    'model' => $searchModel,
                    'attribute' => 'logged_at',
                    'phpDatetimeFormat' => 'dd.MM.yyyy',
                    'momentDatetimeFormat' => 'DD.MM.YYYY',
                    'clientEvents' => [
                        'dp.change' => new JsExpression('(e) => $(e.target).find("input").trigger("change.yiiGridView")'),
                    ],
                ])
            ],
            // 'updated_at',
            [
                'class' => yii\grid\ActionColumn::class,
                //'template' => '{login} {view} {update} {delete}',
                'buttons' => [
                    'login' => function ($url) {
                        return Html::a(
                            '<i class="fa fa-sign-in" aria-hidden="true"></i>',
                            $url,
                            ['title' => Yii::t('backend', 'Login'),]
                        );
                    },
                ],
                'visibleButtons' => [
                    'login' => Yii::$app->user->can('administrator'),
                    'delete' => Yii::$app->user->can('administrator'),
                ],
            ],
        ],
    ]); ?>
</div>
<?php $this->endContent(); ?>